### ISSUE TITLE
"Project has been marked for deletion, please try a few more minutes to try again"

### ISSUE THREAD

**Issue by CarstVaartjes** [quantifiedcode/issues#19]
Hi,

we renamed a repository in github, which made it look rather strange in quantifiedcode (kept the old name). So i deleted it and tried to add it back with the new name but then I get "Project has been marked for deletion, please try a few more minutes to try again".
After 24 hours it still says that :) Could you please look into this?

Thanks!

Carst

**Comment by adewes** [comment]
Hey @CarstVaartjes 

thanks for reporting this, we fixed the issue and deleted all projects, it should work now! Please let us know if you still have problems adding your projects again.

Just so that I understand: You deleted the projects because the permalinks were not updated after you changed the names of your projects on Github? Or was it that the names themselves were not updated on QuantifiedCode?

We're currently implementing a better solution for the permalinks, the main reason that we do not change them right now is that we don't want to break existing links on external sites or emails.

Best
Andreas

**Comment by CarstVaartjes** [comment]
great, thanks! the repository name was not updated on QuantifiedCode and I was unsure if it was just the name, or a more general issue (not being linked anymore). So I thought "let's just remove and add it back again" :)
