### ISSUE TITLE
Status changes from success to failure after PR merge

### ISSUE THREAD

**Issue by dopplershift** [quantifiedcode/issues#65]
After I merge a Pull Request (which is set to use GitHub's "Rebase and Merge" functionality), the status on the last commit changes to failure with the message "We cannot find the commit for this pull requests." You can see an example here:
https://github.com/Unidata/MetPy/pull/252

Github's details on the merge however gives a link that works fine:
https://www.quantifiedcode.com/app/project/gh:Unidata:MetPy/diff/8fc031a5f075e8a588652140e5726b52d982c893/6845319990318292fc7b22bfe8ca39f7131706f3/issues

It'd be nice to not have my PR history show a bunch of red x's.

**Comment by adewes** [comment]
Thanks for reporting this! It seems that we have trouble finding merge commits for pull requests for which you delete the branch and rebase them on top of your master branch. I disabled analysis of merged pull requests, this should fix the problem. Please feel free to close this issue if you think the problem is solved indeed, if not please ping me again.

**Comment by dopplershift** [comment]
Thanks, that seems to be giving me what I want.
