### ISSUE TITLE
Prefer static methods over instance methods looks to be buggy

### ISSUE THREAD

**Issue by sbrunner** [quantifiedcode/issues#66]
Here he don't detect the `@staticmethod`
https://www.quantifiedcode.com/app/project/gh:sbrunner:tilecloud?groups=code_patterns%3A7I7lGdCx%3Af0%3Ao10

**Comment by adewes** [comment]
Thanks for reporting this @sbrunner , there was indeed an edge case that wasn't accounted for in the pattern, which I fixed! I triggered a reset of your project, the pattern should now correctly match the staticmethod decorator. Please close this issue if you think the problem is resolved, and please let me know if it isn't.

**Comment by sbrunner** [comment]
Thanks @adewes :-)
